name: Build

on: [push, workflow_dispatch]


jobs:
  build-mimalloc:
    uses: ./.github/workflows/mimalloc.yml

  build:
    name: Build
    needs: build-mimalloc

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: 'windows-amd64'
            os: 'windows-latest'
        exclude:
          - build_tool: vs
            lto: Thin
          - build_tool: vs
            lto: Full
        build_tool: [clang, vs] #, mingw64, mingw32, mingw-ucrt64, mingw-clang64]
        id: ['windows-amd64']
        llvm_version: ['main', 'llvmorg-18-init-17730-gf670112a']
        llvm_repo_url: ['https://github.com/llvm/llvm-project.git']
        cmake_build_type: ['Release'] # 'MinSizeRel']
        lto: ['Off', 'Thin', 'Full']
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      llvm_version: ${{ matrix.llvm_version }}
      llvm_repo_url: ${{ matrix.llvm_repo_url }}
      build_tool: ${{ matrix.build_tool }}
      lto: ${{ matrix.lto }}
      cmake_build_type: ${{ matrix.cmake_build_type }}
      mimalloc_artifact_name: ${{ needs.build-mimalloc.outputs.artifact }}
      run_id: ${{ github.run_id }}

#  release:
#    name: Release
#
#    runs-on: ubuntu-latest
#    # if: startsWith(github.ref, 'refs/tags/')
#
#    needs: [build]
#
#    permissions:
#      contents: write
#
#    #strategy:
#      #fail-fast: false
#      #matrix:
#      #  llvm_version: ['main', 'llvmorg-18-init-4631-gd50b56d1']
#
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v3
#        with:
#          path: artifacts
#
#      - name: Inspect
#        shell: bash
#        run: |
#          ls -laGiR ./*
#
#      - name: Rename artifacts
#        shell: pwsh
#        run: |
#          Get-ChildItem -Recurse -Path ./artifacts | where { ! $_.PSIsContainer } | ForEach-Object { Move-Item -Path $_ -Destination $($_.FullName -replace 'artifacts[\\/](?<id>.*?)-(?<version>.*?)-(?<buildType>.*?)[\\/]llvm.7z','artifacts/${id}-${version}-${buildType}.7z') }
